name: Shell Commands

on: [push]

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
          - name: echo a string
            run: echo "Hello Shetty"
          - name: multiline script
            run: |
              node -v
              npm -v 
          - name: python command
            run: |
              import platform
              print(platform.processor())
            shell: python  
    run-shell-command-for-windows:
        runs-on: windows-latest
        steps:   
          - name: print current directory
            run: echo $PATH  